#!/usr/bin/env bash
# gen-platform.sh — Generate cross-platform adapter files for flow-code.
# Usage: bash scripts/gen-platform.sh <codex|cursor>
# Idempotent: safe to re-run, overwrites cleanly.
# Dependencies: bash, jq

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CLAUDE_MD="$PLUGIN_ROOT/CLAUDE.md"
PLUGIN_JSON="$PLUGIN_ROOT/.claude-plugin/plugin.json"

# --- helpers ---

die() { printf 'Error: %s\n' "$1" >&2; exit 1; }

require_file() {
  [ -f "$1" ] || die "Required file not found: $1"
}

ensure_dir() {
  mkdir -p "$1"
}

plugin_name() {
  jq -r '.name // "flow-code"' "$PLUGIN_JSON"
}

plugin_version() {
  jq -r '.version // "unknown"' "$PLUGIN_JSON"
}

plugin_description() {
  jq -r '.description // ""' "$PLUGIN_JSON"
}

# Collect skill names and descriptions from SKILL.md frontmatter.
# Outputs: name<TAB>description per line.
collect_skills() {
  local skills_dir="$PLUGIN_ROOT/skills"
  [ -d "$skills_dir" ] || return 0
  for skill_dir in "$skills_dir"/*/; do
    local skill_md="$skill_dir/SKILL.md"
    [ -f "$skill_md" ] || continue
    local name="" desc=""
    local in_frontmatter=0
    while IFS= read -r line; do
      if [[ "$in_frontmatter" -eq 0 && "$line" == "---" ]]; then
        in_frontmatter=1
        continue
      fi
      if [[ "$in_frontmatter" -eq 1 && "$line" == "---" ]]; then
        break
      fi
      if [[ "$in_frontmatter" -eq 1 ]]; then
        if [[ "$line" =~ ^name:\ *(.*) ]]; then
          name="${BASH_REMATCH[1]}"
          # Strip quotes
          name="${name#\"}"
          name="${name%\"}"
          name="${name#\'}"
          name="${name%\'}"
        fi
        if [[ "$line" =~ ^description:\ *(.*) ]]; then
          desc="${BASH_REMATCH[1]}"
          desc="${desc#\"}"
          desc="${desc%\"}"
          desc="${desc#\'}"
          desc="${desc%\'}"
        fi
      fi
    done < "$skill_md"
    [ -n "$name" ] || name="$(basename "$skill_dir")"
    printf '%s\t%s\n' "$name" "$desc"
  done
}

# Collect agent names and descriptions from agent .md frontmatter.
collect_agents() {
  local agents_dir="$PLUGIN_ROOT/agents"
  [ -d "$agents_dir" ] || return 0
  for agent_md in "$agents_dir"/*.md; do
    [ -f "$agent_md" ] || continue
    local name="" desc=""
    local in_frontmatter=0
    while IFS= read -r line; do
      if [[ "$in_frontmatter" -eq 0 && "$line" == "---" ]]; then
        in_frontmatter=1
        continue
      fi
      if [[ "$in_frontmatter" -eq 1 && "$line" == "---" ]]; then
        break
      fi
      if [[ "$in_frontmatter" -eq 1 ]]; then
        if [[ "$line" =~ ^name:\ *(.*) ]]; then
          name="${BASH_REMATCH[1]}"
          name="${name#\"}"
          name="${name%\"}"
          name="${name#\'}"
          name="${name%\'}"
        fi
        if [[ "$line" =~ ^description:\ *(.*) ]]; then
          desc="${BASH_REMATCH[1]}"
          desc="${desc#\"}"
          desc="${desc%\"}"
          desc="${desc#\'}"
          desc="${desc%\'}"
        fi
      fi
    done < "$agent_md"
    [ -n "$name" ] || name="$(basename "$agent_md" .md)"
    printf '%s\t%s\n' "$name" "$desc"
  done
}

# Collect command names and descriptions from command .md files.
collect_commands() {
  local cmds_dir="$PLUGIN_ROOT/commands/flow-code"
  [ -d "$cmds_dir" ] || return 0
  for cmd_md in "$cmds_dir"/*.md; do
    [ -f "$cmd_md" ] || continue
    local name="" desc=""
    local in_frontmatter=0
    while IFS= read -r line; do
      if [[ "$in_frontmatter" -eq 0 && "$line" == "---" ]]; then
        in_frontmatter=1
        continue
      fi
      if [[ "$in_frontmatter" -eq 1 && "$line" == "---" ]]; then
        break
      fi
      if [[ "$in_frontmatter" -eq 1 ]]; then
        if [[ "$line" =~ ^name:\ *(.*) ]]; then
          name="${BASH_REMATCH[1]}"
          name="${name#\"}"
          name="${name%\"}"
          name="${name#\'}"
          name="${name%\'}"
        fi
        if [[ "$line" =~ ^description:\ *(.*) ]]; then
          desc="${BASH_REMATCH[1]}"
          desc="${desc#\"}"
          desc="${desc%\"}"
          desc="${desc#\'}"
          desc="${desc%\'}"
        fi
      fi
    done < "$cmd_md"
    [ -n "$name" ] || name="$(basename "$cmd_md" .md)"
    printf '%s\t%s\n' "$name" "$desc"
  done
}

# --- codex target ---

generate_codex() {
  local out_dir="$PLUGIN_ROOT/.codex"
  ensure_dir "$out_dir"

  local name version desc
  name="$(plugin_name)"
  version="$(plugin_version)"
  desc="$(plugin_description)"

  # Build AGENTS.md
  {
    cat <<HEADER
# Agent Instructions — $name (Codex adapter)

> Auto-generated by \`scripts/gen-platform.sh codex\`. Safe to re-run.
> Source plugin: $name v$version

## Overview

$desc

## Setup

This directory was generated from a Claude Code plugin. The canonical source of truth
is \`CLAUDE.md\` at the repository root. Key differences for Codex:

- **flowctl binary**: The task engine lives at \`bin/flowctl\`. Invoke it directly:
  \`\`\`bash
  ./bin/flowctl <command>
  \`\`\`
- **No slash commands**: Codex does not support \`/plugin:command\` syntax. Use the
  skill descriptions below to understand available capabilities.
- **No hooks**: Codex does not support lifecycle hooks. Guard checks must be run manually.

## Primary Workflow

1. Plan: Create an epic with tasks — \`./bin/flowctl epic create "description"\`
2. Work: Pick next task — \`./bin/flowctl next\`
3. Complete: Mark done with evidence — \`./bin/flowctl done <task-id> --summary-file <f> --evidence-json <j>\`

## Architecture

\`\`\`
CLAUDE.md              → Project instructions (read this first)
bin/flowctl            → Rust binary — single source of truth for .flow/ state
commands/flow-code/    → Slash command definitions (Claude Code specific)
skills/*/SKILL.md      → Skill implementations (reusable across platforms)
agents/*.md            → Subagent definitions
\`\`\`

HEADER

    # Commands section
    printf '## Commands\n\n'
    printf 'These map to Claude Code slash commands (`/flow-code:<name>`).\n'
    printf 'In Codex, invoke the underlying skill or flowctl command directly.\n\n'
    printf '| Command | Description |\n'
    printf '|---------|-------------|\n'
    while IFS=$'\t' read -r cname cdesc; do
      printf '| %s | %s |\n' "$cname" "$cdesc"
    done < <(collect_commands)
    printf '\n'

    # Skills section
    printf '## Skills\n\n'
    printf 'Skills are loaded by the Skill tool in Claude Code. In Codex, read the\n'
    printf 'corresponding `skills/<name>/SKILL.md` for detailed instructions.\n\n'
    printf '| Skill | Description |\n'
    printf '|-------|-------------|\n'
    while IFS=$'\t' read -r sname sdesc; do
      printf '| %s | %s |\n' "$sname" "$sdesc"
    done < <(collect_skills)
    printf '\n'

    # Agents section
    printf '## Agents\n\n'
    printf 'Agents are spawned as subagents in Claude Code. In Codex, read the\n'
    printf 'corresponding `agents/<name>.md` for instructions.\n\n'
    printf '| Agent | Description |\n'
    printf '|-------|-------------|\n'
    while IFS=$'\t' read -r aname adesc; do
      printf '| %s | %s |\n' "$aname" "$adesc"
    done < <(collect_agents)
    printf '\n'

    # Key design decisions — excerpt from CLAUDE.md
    printf '## Key Design Decisions\n\n'
    printf 'See `CLAUDE.md` for the full list. Highlights:\n\n'
    printf -- '- flowctl outputs JSON (`--json` flag) for machine consumption\n'
    printf -- '- Tasks follow `todo -> in_progress -> done` state machine\n'
    printf -- '- Evidence-based completion: `flowctl done` requires `--summary-file` and `--evidence-json`\n'
    printf -- '- File locking prevents concurrent edits in Teams mode\n'
    printf -- '- Three-layer quality: guard (lint/test) + plan-review + adversarial review\n'

  } > "$out_dir/AGENTS.md"

  printf 'Generated %s\n' "$out_dir/AGENTS.md"
}

# --- cursor target ---

generate_cursor() {
  local out_dir="$PLUGIN_ROOT/.cursor/rules"
  ensure_dir "$out_dir"

  local name version
  name="$(plugin_name)"
  version="$(plugin_version)"

  # Rule 1: Project overview from CLAUDE.md
  {
    cat <<'RULE_HEADER'
---
description: Flow-code project overview and architecture
globs:
alwaysApply: true
---

RULE_HEADER
    # Include CLAUDE.md content directly
    cat "$CLAUDE_MD"
  } > "$out_dir/flow-code-overview.mdc"
  printf 'Generated %s\n' "$out_dir/flow-code-overview.mdc"

  # Rule 2: flowctl usage
  {
    cat <<'RULE_HEADER'
---
description: How to use the flowctl CLI for task management
globs:
  - "flowctl/**"
  - ".flow/**"
  - "scripts/*.sh"
alwaysApply: false
---

RULE_HEADER
    cat <<'BODY'
# flowctl CLI Reference

flowctl is the Rust binary that manages `.flow/` state. Always invoke from the repo root:

```bash
./bin/flowctl <command>
```

## Common Commands

- `epic create "description"` — Create a new epic
- `epic list` — List all epics
- `tasks --epic <id>` — List tasks for an epic
- `next [--epic <id>]` — Get the next ready task
- `start <task-id>` — Mark task as in-progress
- `done <task-id> --summary-file <f> --evidence-json <j>` — Complete a task
- `restart <task-id>` — Reset a task and cascade to dependents
- `task skip <id> --reason "why"` — Skip a task
- `task split <id> --titles "A|B|C" --chain` — Split into sub-tasks
- `lock --task <id> --files <paths>` — Acquire file locks
- `unlock --task <id>` — Release file locks
- `guard` — Run lint/type/test checks
- `codex adversarial --base main` — Adversarial review via Codex
- `status --interrupted` — Check for unfinished work

## State Machine

Tasks: `todo` -> `in_progress` -> `done` (with `blocked` and `skipped` side-states)

## Output

Use `--json` for machine-readable JSON output.
BODY
  } > "$out_dir/flow-code-flowctl.mdc"
  printf 'Generated %s\n' "$out_dir/flow-code-flowctl.mdc"

  # Rule 3: Skills index
  {
    cat <<'RULE_HEADER'
---
description: Flow-code available skills and their purposes
globs:
  - "skills/**"
alwaysApply: false
---

RULE_HEADER
    printf '# Flow-code Skills\n\n'
    printf 'Each skill lives in `skills/<name>/SKILL.md`. Read the SKILL.md for full instructions.\n\n'
    printf '| Skill | Description |\n'
    printf '|-------|-------------|\n'
    while IFS=$'\t' read -r sname sdesc; do
      printf '| %s | %s |\n' "$sname" "$sdesc"
    done < <(collect_skills)
  } > "$out_dir/flow-code-skills.mdc"
  printf 'Generated %s\n' "$out_dir/flow-code-skills.mdc"

  # Rule 4: Agents index
  {
    cat <<'RULE_HEADER'
---
description: Flow-code available agents and their purposes
globs:
  - "agents/**"
alwaysApply: false
---

RULE_HEADER
    printf '# Flow-code Agents\n\n'
    printf 'Each agent lives in `agents/<name>.md`. Read the file for full instructions.\n\n'
    printf '| Agent | Description |\n'
    printf '|-------|-------------|\n'
    while IFS=$'\t' read -r aname adesc; do
      printf '| %s | %s |\n' "$aname" "$adesc"
    done < <(collect_agents)
  } > "$out_dir/flow-code-agents.mdc"
  printf 'Generated %s\n' "$out_dir/flow-code-agents.mdc"

  # Rule 5: Code quality
  {
    cat <<'RULE_HEADER'
---
description: Code quality and testing rules for flow-code
globs:
  - "flowctl/**"
  - "scripts/**"
  - "hooks/**"
alwaysApply: false
---

RULE_HEADER
    cat <<'BODY'
# Code Quality Rules

## Build and Test

```bash
cd flowctl && cargo build --release && cargo test --all
```

## Validation

```bash
python3 -c "import json; json.load(open('hooks/hooks.json'))"
```

## Testing

```bash
bash scripts/smoke_test.sh      # flowctl core
bash scripts/ci_test.sh          # full CI
bash scripts/teams_e2e_test.sh   # Teams file locking
```

All tests create temp directories and clean up. Must NOT run from the plugin repo root.

## Files to Never Commit

- `ref/` — reference/backup repos
- `*.upstream` — upstream backup files
- `.tasks/` — runtime state
- `__pycache__/` — Python cache
- `.flow/` — per-project task state
BODY
  } > "$out_dir/flow-code-quality.mdc"
  printf 'Generated %s\n' "$out_dir/flow-code-quality.mdc"
}

# --- main ---

main() {
  if [ $# -lt 1 ]; then
    cat >&2 <<USAGE
Usage: bash scripts/gen-platform.sh <codex|cursor>

Targets:
  codex   Generate .codex/ directory with AGENTS.md
  cursor  Generate .cursor/rules/ with .mdc rules files
USAGE
    exit 1
  fi

  require_file "$CLAUDE_MD"
  require_file "$PLUGIN_JSON"

  case "$1" in
    codex)
      generate_codex
      ;;
    cursor)
      generate_cursor
      ;;
    *)
      die "Unknown target: $1 (expected 'codex' or 'cursor')"
      ;;
  esac

  printf 'Done.\n'
}

main "$@"
