//! Codex sync: convert Claude Code agent `.md` files to OpenAI Codex `.toml` format.
//!
//! Used by `flowctl codex sync` to generate a `.codex-plugin/` directory from
//! the plugin's `agents/` Markdown definitions.

use std::path::Path;

use serde::Deserialize;

use crate::error::CoreError;
use crate::frontmatter;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/// Frontmatter fields expected in an agent `.md` file.
#[derive(Debug, Clone, Deserialize)]
pub struct AgentFrontmatter {
    pub name: String,
    pub description: String,
    pub model: String,
    #[serde(rename = "disallowedTools", default)]
    pub disallowed_tools: Option<String>,
    pub color: Option<String>,
}

/// Result of mapping a Claude model string to Codex equivalents.
#[derive(Debug, Clone)]
pub struct ModelMapping {
    pub codex_model: String,
    pub reasoning_effort: Option<String>,
}

/// Summary returned by [`sync_all`].
#[derive(Debug, Default)]
pub struct SyncSummary {
    pub agents_generated: usize,
    pub agents_skipped: usize,
    pub hooks_generated: bool,
    pub errors: Vec<String>,
}

// ---------------------------------------------------------------------------
// Intelligent-scout list
// ---------------------------------------------------------------------------

/// Scouts that should use the *intelligent* model even when their agent
/// definition says "sonnet".
const INTELLIGENT_SCOUTS: &[&str] = &["epic-scout", "claude-md-scout", "docs-gap-scout"];

// ---------------------------------------------------------------------------
// Model mapping
// ---------------------------------------------------------------------------

fn intelligent_model() -> String {
    std::env::var("CODEX_MODEL_INTELLIGENT").unwrap_or_else(|_| "gpt-5.4".to_string())
}

fn fast_model() -> String {
    std::env::var("CODEX_MODEL_FAST").unwrap_or_else(|_| "gpt-5.4-mini".to_string())
}

/// Map a Claude model identifier to a Codex model + optional reasoning effort.
pub fn map_model(claude_model: &str, agent_name: &str) -> ModelMapping {
    let lower = claude_model.to_lowercase();

    if lower == "opus" || lower.starts_with("claude-opus") {
        ModelMapping {
            codex_model: intelligent_model(),
            reasoning_effort: Some("high".to_string()),
        }
    } else if lower == "sonnet" || lower.starts_with("claude-sonnet") {
        if INTELLIGENT_SCOUTS.contains(&agent_name) {
            ModelMapping {
                codex_model: intelligent_model(),
                reasoning_effort: Some("high".to_string()),
            }
        } else {
            ModelMapping {
                codex_model: fast_model(),
                reasoning_effort: None,
            }
        }
    } else if lower == "haiku" || lower.starts_with("claude-haiku") {
        ModelMapping {
            codex_model: fast_model(),
            reasoning_effort: None,
        }
    } else if lower == "inherit" || lower.is_empty() {
        ModelMapping {
            codex_model: String::new(),
            reasoning_effort: None,
        }
    } else {
        ModelMapping {
            codex_model: intelligent_model(),
            reasoning_effort: Some("high".to_string()),
        }
    }
}

// ---------------------------------------------------------------------------
// Sandbox
// ---------------------------------------------------------------------------

/// Return the Codex sandbox mode for a given agent name.
pub fn sandbox_for(name: &str) -> &'static str {
    match name {
        "worker" | "plan-sync" => "workspace-write",
        _ => "read-only",
    }
}

// ---------------------------------------------------------------------------
// TOML generation
// ---------------------------------------------------------------------------

/// Generate the `.toml` content for a single agent.
///
/// Built manually (not via serde) because `developer_instructions` uses
/// TOML multi-line basic strings (`"""`).
pub fn generate_agent_toml(
    fm: &AgentFrontmatter,
    body: &str,
    mapping: &ModelMapping,
) -> String {
    let escaped_body = body.replace('\\', "\\\\");
    let sandbox = sandbox_for(&fm.name);

    let mut out = String::with_capacity(256 + escaped_body.len());
    out.push_str("# Auto-generated by flowctl codex sync — do not edit manually\n");
    out.push_str(&format!("name = {:?}\n", fm.name));
    out.push_str(&format!("description = {:?}\n", fm.description));

    if !mapping.codex_model.is_empty() {
        out.push_str(&format!("model = {:?}\n", mapping.codex_model));
    }
    if let Some(ref effort) = mapping.reasoning_effort {
        out.push_str(&format!("model_reasoning_effort = {:?}\n", effort));
    }

    out.push_str(&format!("sandbox_mode = {:?}\n", sandbox));
    out.push_str(&format!(
        "\ndeveloper_instructions = \"\"\"\n{}\"\"\"\n",
        escaped_body
    ));
    out
}

// ---------------------------------------------------------------------------
// Plugin / marketplace JSON
// ---------------------------------------------------------------------------

/// Generate `.codex-plugin/plugin.json`.
pub fn generate_plugin_json(version: &str, name: &str, description: &str) -> String {
    serde_json::json!({
        "schema_version": "v1",
        "name": name,
        "description": description,
        "version": version
    })
    .to_string()
}

/// Generate `.agents/plugins/marketplace.json`.
pub fn generate_marketplace_json(plugin_name: &str) -> String {
    serde_json::json!({
        "plugins": [
            { "name": plugin_name, "path": ".codex-plugin" }
        ]
    })
    .to_string()
}

// ---------------------------------------------------------------------------
// Hooks patching
// ---------------------------------------------------------------------------

/// Patch a Claude Code `hooks.json` for Codex: replace `"Bash"` matchers
/// with `"Bash|Execute"`.
pub fn generate_hooks_json(source_hooks: &str) -> Result<String, CoreError> {
    let mut value: serde_json::Value = serde_json::from_str(source_hooks)
        .map_err(|e| CoreError::FrontmatterParse(format!("hooks JSON parse error: {e}")))?;

    patch_bash_matchers(&mut value);

    serde_json::to_string_pretty(&value)
        .map_err(|e| CoreError::FrontmatterParse(format!("hooks JSON serialize error: {e}")))
}

/// Recursively walk the JSON value and replace `"Bash"` strings with
/// `"Bash|Execute"` wherever they appear.
fn patch_bash_matchers(value: &mut serde_json::Value) {
    match value {
        serde_json::Value::String(s) if s == "Bash" => {
            *s = "Bash|Execute".to_string();
        }
        serde_json::Value::Array(arr) => {
            for item in arr.iter_mut() {
                patch_bash_matchers(item);
            }
        }
        serde_json::Value::Object(map) => {
            for v in map.values_mut() {
                patch_bash_matchers(v);
            }
        }
        _ => {}
    }
}

// ---------------------------------------------------------------------------
// sync_all
// ---------------------------------------------------------------------------

/// Synchronise all agent `.md` files into Codex `.toml` files.
///
/// If `dry_run` is true, no files are written but the summary still reflects
/// what *would* happen.
pub fn sync_all(
    agents_dir: &Path,
    hooks_path: Option<&Path>,
    output_dir: &Path,
    dry_run: bool,
) -> Result<SyncSummary, CoreError> {
    let mut summary = SyncSummary::default();

    let agents_out = output_dir.join("agents");
    if !dry_run {
        std::fs::create_dir_all(&agents_out).map_err(|e| {
            CoreError::FrontmatterParse(format!("cannot create output dir: {e}"))
        })?;
    }

    // Read all .md files from agents_dir
    let entries = std::fs::read_dir(agents_dir).map_err(|e| {
        CoreError::FrontmatterParse(format!("cannot read agents dir: {e}"))
    })?;

    for entry in entries {
        let entry = match entry {
            Ok(e) => e,
            Err(e) => {
                summary.errors.push(format!("readdir error: {e}"));
                summary.agents_skipped += 1;
                continue;
            }
        };

        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("md") {
            continue;
        }

        let content = match std::fs::read_to_string(&path) {
            Ok(c) => c,
            Err(e) => {
                summary
                    .errors
                    .push(format!("{}: read error: {e}", path.display()));
                summary.agents_skipped += 1;
                continue;
            }
        };

        let doc = match frontmatter::parse::<AgentFrontmatter>(&content) {
            Ok(d) => d,
            Err(e) => {
                summary
                    .errors
                    .push(format!("{}: parse error: {e}", path.display()));
                summary.agents_skipped += 1;
                continue;
            }
        };

        let mapping = map_model(&doc.frontmatter.model, &doc.frontmatter.name);
        let toml_content = generate_agent_toml(&doc.frontmatter, &doc.body, &mapping);

        if !dry_run {
            let out_path = agents_out.join(format!("{}.toml", doc.frontmatter.name));
            std::fs::write(&out_path, &toml_content).map_err(|e| {
                CoreError::FrontmatterParse(format!(
                    "cannot write {}: {e}",
                    out_path.display()
                ))
            })?;
        }

        summary.agents_generated += 1;
    }

    // Hooks
    if let Some(hp) = hooks_path {
        if hp.exists() {
            match std::fs::read_to_string(hp) {
                Ok(src) => match generate_hooks_json(&src) {
                    Ok(patched) => {
                        if !dry_run {
                            let hooks_out = output_dir.join("hooks.json");
                            std::fs::write(&hooks_out, &patched).map_err(|e| {
                                CoreError::FrontmatterParse(format!(
                                    "cannot write hooks: {e}"
                                ))
                            })?;
                        }
                        summary.hooks_generated = true;
                    }
                    Err(e) => {
                        summary.errors.push(format!("hooks patch error: {e}"));
                    }
                },
                Err(e) => {
                    summary.errors.push(format!("hooks read error: {e}"));
                }
            }
        }
    }

    Ok(summary)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_map_model_opus() {
        let m = map_model("opus", "worker");
        assert_eq!(m.codex_model, "gpt-5.4");
        assert_eq!(m.reasoning_effort.as_deref(), Some("high"));
    }

    #[test]
    fn test_map_model_sonnet_fast() {
        let m = map_model("sonnet", "worker");
        assert_eq!(m.codex_model, "gpt-5.4-mini");
        assert!(m.reasoning_effort.is_none());
    }

    #[test]
    fn test_map_model_sonnet_intelligent_scout() {
        let m = map_model("sonnet", "epic-scout");
        assert_eq!(m.codex_model, "gpt-5.4");
        assert_eq!(m.reasoning_effort.as_deref(), Some("high"));
    }

    #[test]
    fn test_map_model_haiku() {
        let m = map_model("haiku", "worker");
        assert_eq!(m.codex_model, "gpt-5.4-mini");
        assert!(m.reasoning_effort.is_none());
    }

    #[test]
    fn test_map_model_inherit() {
        let m = map_model("inherit", "worker");
        assert!(m.codex_model.is_empty());
        assert!(m.reasoning_effort.is_none());
    }

    #[test]
    fn test_map_model_empty() {
        let m = map_model("", "worker");
        assert!(m.codex_model.is_empty());
        assert!(m.reasoning_effort.is_none());
    }

    #[test]
    fn test_sandbox_for_worker() {
        assert_eq!(sandbox_for("worker"), "workspace-write");
        assert_eq!(sandbox_for("plan-sync"), "workspace-write");
    }

    #[test]
    fn test_sandbox_for_scout() {
        assert_eq!(sandbox_for("epic-scout"), "read-only");
        assert_eq!(sandbox_for("anything"), "read-only");
    }

    #[test]
    fn test_generate_agent_toml_basic() {
        let fm = AgentFrontmatter {
            name: "test-agent".to_string(),
            description: "A test agent".to_string(),
            model: "opus".to_string(),
            disallowed_tools: None,
            color: None,
        };
        let mapping = ModelMapping {
            codex_model: "gpt-5.4".to_string(),
            reasoning_effort: Some("high".to_string()),
        };
        let toml = generate_agent_toml(&fm, "Do stuff.\n", &mapping);
        assert!(toml.contains("name = \"test-agent\""));
        assert!(toml.contains("model = \"gpt-5.4\""));
        assert!(toml.contains("model_reasoning_effort = \"high\""));
        assert!(toml.contains("sandbox_mode = \"read-only\""));
        assert!(toml.contains("Do stuff."));
    }

    #[test]
    fn test_generate_agent_toml_no_reasoning() {
        let fm = AgentFrontmatter {
            name: "worker".to_string(),
            description: "Worker".to_string(),
            model: "sonnet".to_string(),
            disallowed_tools: None,
            color: None,
        };
        let mapping = ModelMapping {
            codex_model: "gpt-5.4-mini".to_string(),
            reasoning_effort: None,
        };
        let toml = generate_agent_toml(&fm, "body\n", &mapping);
        assert!(!toml.contains("model_reasoning_effort"));
        assert!(toml.contains("sandbox_mode = \"workspace-write\""));
    }

    #[test]
    fn test_generate_agent_toml_escapes_backslashes() {
        let fm = AgentFrontmatter {
            name: "esc".to_string(),
            description: "d".to_string(),
            model: "opus".to_string(),
            disallowed_tools: None,
            color: None,
        };
        let mapping = ModelMapping {
            codex_model: "gpt-5.4".to_string(),
            reasoning_effort: None,
        };
        let toml = generate_agent_toml(&fm, "path\\to\\thing\n", &mapping);
        assert!(toml.contains("path\\\\to\\\\thing"));
    }

    #[test]
    fn test_generate_plugin_json() {
        let json = generate_plugin_json("1.0.0", "flow-code", "A plugin");
        assert!(json.contains("flow-code"));
        assert!(json.contains("1.0.0"));
    }

    #[test]
    fn test_generate_marketplace_json() {
        let json = generate_marketplace_json("flow-code");
        assert!(json.contains("flow-code"));
        assert!(json.contains(".codex-plugin"));
    }

    #[test]
    fn test_generate_hooks_json_patches_bash() {
        let input = r#"{"hooks":[{"matcher":"Bash","command":"echo hi"}]}"#;
        let out = generate_hooks_json(input).unwrap();
        assert!(out.contains("Bash|Execute"));
        assert!(!out.contains("\"Bash\""));
    }

    #[test]
    fn test_generate_hooks_json_invalid() {
        let result = generate_hooks_json("not json");
        assert!(result.is_err());
    }

    #[test]
    fn test_parse_agent_valid() {
        let content = "---\nname: my-agent\ndescription: A test agent\nmodel: opus\ndisallowedTools: Edit, Write\ncolor: blue\n---\nBody instructions here.\n";
        let doc = frontmatter::parse::<AgentFrontmatter>(content).unwrap();
        assert_eq!(doc.frontmatter.name, "my-agent");
        assert_eq!(doc.frontmatter.description, "A test agent");
        assert_eq!(doc.frontmatter.model, "opus");
        assert_eq!(doc.frontmatter.disallowed_tools.as_deref(), Some("Edit, Write"));
        assert_eq!(doc.frontmatter.color.as_deref(), Some("blue"));
        assert!(doc.body.contains("Body instructions here."));
    }

    #[test]
    fn test_parse_agent_no_frontmatter() {
        let content = "No frontmatter at all, just plain text.";
        let result = frontmatter::parse::<AgentFrontmatter>(content);
        assert!(result.is_err());
    }

    #[test]
    fn test_parse_agent_invalid_yaml() {
        let content = "---\n: : : not valid yaml [[[{\n---\nBody.\n";
        let result = frontmatter::parse::<AgentFrontmatter>(content);
        assert!(result.is_err());
    }

    #[test]
    fn test_parse_agent_missing_model() {
        let content = "---\nname: incomplete\ndescription: Missing model field\n---\nBody.\n";
        let result = frontmatter::parse::<AgentFrontmatter>(content);
        assert!(result.is_err());
    }

    #[test]
    fn test_sync_all_dry_run() {
        let dir = tempfile::tempdir().unwrap();
        let agents = dir.path().join("agents");
        std::fs::create_dir(&agents).unwrap();

        // Write a valid agent md
        std::fs::write(
            agents.join("test-scout.md"),
            "---\nname: test-scout\ndescription: A scout\nmodel: sonnet\n---\nBody here.\n",
        )
        .unwrap();

        // Write an invalid file (should be skipped)
        std::fs::write(agents.join("bad.md"), "no frontmatter").unwrap();

        let out = dir.path().join("out");
        let summary = sync_all(&agents, None, &out, true).unwrap();
        assert_eq!(summary.agents_generated, 1);
        assert_eq!(summary.agents_skipped, 1);
        // Dry run: no output files
        assert!(!out.exists());
    }

    #[test]
    fn test_sync_all_writes_files() {
        let dir = tempfile::tempdir().unwrap();
        let agents = dir.path().join("agents");
        std::fs::create_dir(&agents).unwrap();

        std::fs::write(
            agents.join("worker.md"),
            "---\nname: worker\ndescription: Worker agent\nmodel: inherit\n---\nDo work.\n",
        )
        .unwrap();

        let out = dir.path().join("out");
        let summary = sync_all(&agents, None, &out, false).unwrap();
        assert_eq!(summary.agents_generated, 1);
        assert!(out.join("agents/worker.toml").exists());

        let content = std::fs::read_to_string(out.join("agents/worker.toml")).unwrap();
        assert!(content.contains("name = \"worker\""));
    }
}
